# Generated by Django 2.2.6 on 2019-10-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191004_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ultimo_nome',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
