# Generated by Django 2.2.6 on 2019-10-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191005_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_numero', models.CharField(max_length=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=3, max_digits=7)),
                ('client', models.ForeignKey(on_delete=False, to='core.Client')),
            ],
        ),
    ]
